
name: openblas-src-linux

on:
  workflow_dispatch: {}

jobs:
  

  linux:
    runs-on: ubuntu-latest
    container:
      image: rust
    strategy:
      fail-fast: false
      matrix:
        feature:
          # - ""
          # - static
          - static
        target: [x86_64, aarch64]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: 'recursive'
    - name: Install gfortran by apt
      run: |
        apt update
        apt install -y gfortran
    # - name: Install OpenBLAS by apt
    #   run: |
    #     apt update
    #     apt install -y libopenblas-dev
    #   if: ${{ contains(matrix.feature, 'system') }}
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: >
          --verbose
          --release
          --features=${{ matrix.feature }}
          --manifest-path=openblas-src/Cargo.toml
